### ISSUE TITLE
CLI `stop` command impacts and removes other docker containers on host

### ISSUE THREAD

**Issue by mike-wendt** [graphistry/graphistry-cli#12]
https://github.com/graphistry/graphistry-cli/blob/f53f3cbf8bbe17a153292b274cc2ce2b5f811509/graphistry/cluster.py#L189

The above line should be restricted to look for only Graphistry containers, so existing containers that are on the system are not impacted when using this tool. 

As it is now running `stop` removes all containers on the host including those that are non-Graphistry related.

**Comment by lmeyerov** [comment]
@mike-wendt  Thanks! The CLI was written assuming whole cloud instance, so I suspect we may have this issue in a couple other spots, e.g., docs.
